### PR TITLE
New command structure using SimpleCommand

### PR DESCRIPTION
**Pull request by oriolbcn**
Result from the discusssion we had in the Martian Day

### CODE REVIEW

**Review by xredo — APPROVED** [review]

**Review by dvdgs88 — APPROVED** [review]

**Review by danigb — APPROVED** [review]
I've been in favor of using SimpleCommand, so I'm happy with the change. The pattern explanation looks right to me 👍

**Comment by jlestebanez** [comment]
Like we talked on the Martian day, I am used to using SimpleCommand pattern so I am very happy with this decision. The explanation is simple and clear.

**Review by jlestebanez — APPROVED** [review]
Like we talked on the Martian day, I am used to using SimpleCommand pattern so I am very happy with this decision. The explanation is simple and clear.

**Review by ItsGenis — APPROVED** [review]

**Comment by waiting-for-dev** [comment]
Hey, as a freelance I dint't take part in the Martian Day, so first of all let me apologize if I'm a little bit out of place here. But everyone in the company has always been very kind to me, inviting me to collaborate in everything I could feel inclined to, so with your consent I'd like to have my two cents worth.

I'd like to bring to the conversation a well known bogeyman: monads, but just to remove straightaway their scary aureole. Monads can be seen from a lot of angles and fundamentally they're a mathematical abstraction which, as any abstraction, is difficult to grasp (and I don't do, for what is worth). But in the same way that you don't need to know the fundamentals of linguistics before beginning to talk, you can use monads just because they're very useful.

One of the use cases monads cover are error handling, which is what commands are about in big part. I'd like to talk about the possibility of using [dry-monads](https://dry-rb.org/gems/dry-monads/1.3/) to build our command objects. Here I rewrite the example in this PR with it:

```ruby
require 'dry/monads'

module Users
  class Update # (1)
 
    include Dry::Monads[:result]

    def initialize(user, params) # (4)
      @user = user
      @params = params
    end

    def call # (5)
      if @user.update(@params)
        some_private_method
        Success(@user)
      else
        some_more_stuff
        Failure(@user)
      end
    end

  end
end

class UsersController < ApplicationController

  def update
    authorize User

    # with Ruby 2.7 pattern matching feature
    case Users::Update.new(user, user_params).call # (1)
    when Success(_)
      redirect_to dashboard_path # (2)
    when Failure(user)
      flash.now[:error] = t('.error', errors: user.errors)
      render :new
    end
  end

end
```

Some reasons why I think it'd be a better approach:

- I think the interface in `dry-monads` is more explicit than in `simple_command`, where you need to know that there's an `errors` accessor available. A thing I find quite obscure is how `@user` is being made available in the failure scenario.
- `simple_command` has a rigid structure. You need to fit your use case into it. It's clearly thought to be used with `ActiveModel` models, where you'll have an instance without errors or an error hash. But you may need a command for different workflows, and it won't fit that well. For example, the `errors` needs to be something like a hash, but what about if you need some other richer data structure? With `dry-monads` you can use the types you want regardless of success or failure.
- Related to the previous point. Sometimes you don't even need to track the errors, in which case you cold use `Dry::Monads::Maybe` and don't complicate things.

In fact, in the previous example we didt't use monads at all. `Dry::Monad::Result` is just a data type. But the error handling becomes very clear once you use `bind` method (which is the monad sugar). For example, a lot of times you need to perform some side effects only when some previous operations succeed. With `dry-monads` you could do something like this (note: here `bind` method is under the hood of the `do` notation, which makes everything more clear):

```ruby
require 'dry/monads'
require 'dry/monads/do'

module Users
  class Update # (1)
 
    include Dry::Monads[:result]
    include Dry::Monads::Do.for(:call)

    def initialize(user, params) # (4)
      @user = user
      @params = params
    end

    def call # (5)
      user = yield persist_user(@user)
      count = yield update_counter
      send_email(user)
      Success(user: user, count: count) 
    end

   private

   def persist_user
     if @user.update(@params)
      Success(@user)
    else
      Failure(:i_dont_even_saved_the_user)
    end
   end

  def update_counter
    if Redis.increament_some_dummy_counter
      Success(:ok)
    else
      Failure(:oops_i_failed_on_redis)
    end
  end

  def send_email(user)
    EmailEngine.send_email_in_the_background(user)
    Success(:ok)
  end
end
```

Sorry for the contrived example, I'm always awful with them :sweat_smile: The thing is that each line in `#call` will be executed when previous ones have returned a `Success`. Once a `Failure` is found, the chain is stopped. If the execution reaches the end, it will return the user and count wrapped in a `Success`, otherwise any of the failures encountered in the way. As you see it gives you all the flexibility in the world to deal with errors while still writing a clear code that focuses in the happy way.

**Comment by danigb** [comment]
Hi Marc!

Nice to have you here! 🎉 

I liked a lot your examples, specially the last one. It's the first time I see in ruby this kind of flexibility: combining seamlessly several methods with two paths of execution. Nice! I find that second example also quite readable.

But as a casual ruby developer (hope! 😅) I find the first example as obscure or more than the simple_command version. You have to know that `errors` exists, but in your example, you have to know where Success and Failure comes from (that's a problem of ruby, not `dry` specific). Not to mention the scary when reading M-O-N-A-D. Jokes aside, I think for most Rails developers, having a _hidden_ error field is quite common.

In my own experience, I've found that getting too far out of the way Rails way of doing makes more troubles than problem solves. Mostly because a) most of the project has legacy code written in Rails style b) other developers with a completely different background might jump into the project and having to learn new libraries or patters slows all the process.

(As a rant, I don't see how ruby can evolve if no-new paradigms are explored, and it looks like `dry` library is doing quite well)

So, I'd take the conservative way of using an old and static library (although I'd happy try `dry` if everyones agrees)

**Comment by waiting-for-dev** [comment]
Hi @danigb !

Thanks a lot for your warm welcome and you follow-up!

I've contradictory feelings with the comments you brought up. I agree in some part, but at the same time they get me frustrated. I mean, I admit that getting off the Rails Way brings some problems. As you say, adding developers to a project written in that style would be less friction-less that just doing what everybody else is doing. But, at the same time, as a developer I take pleasure in trying to do things in the way I think it's better for the code.

Anyway, IMHO I think that in Rails we usually fall in short-sighted predictions. Rails allows you to create a blog engine in 5 minutes and during that 5 minutes you're a very happy programmer. Now the blog engine grows and it's a blog + e-commerce + accountancy software... Now everything is more of a nightmare to maintain and the developer doesn't feel so happy anymore. Investing time in learning new technologies has a cost. Developers can feel more frustrated at the beginning as they don't understand the new process. But, in the long term, everything is easier to maintain (so you recover the cost) and developers are happier as they learned new skills.

> But as a casual ruby developer (hope! ￼) I find the first example as obscure or more than the simple_command version. You have to know that errors exists, but in your example, you have to know where Success and Failure comes from (that's a problem of ruby, not dry specific).

I think that everything that is new feels more obscure that anything else at first sight. But it changes once you're familiar. Anyway, in that example I used pattern matching because is something really concise and beautiful once you get used to it. However, you can write it in a more idiomatic way (through pattern matching is present in ruby 2.7, so it's also idiomatic :wink: ):

```ruby
  def update
    authorize User

    result = Users::Update.new(user, user_params).call # (1)
    if result.success?
      redirect_to dashboard_path # (2)
    else
      user = result.failure
      flash.now[:error] = t('.error', errors: user.errors)
      render :new
    end
  end
```

**Pull request merged**
